version: 2
jobs:
  js_test:
    working_directory: ~/ui-components
    docker:
      - image: circleci/node:14
        environment:
          ENV: CI
    steps:
      - checkout
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          working_directory: ~/ui-components
          name: Run JavaScript tests
          command: npm run test-ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "./reports"

    js_build:
      working_directory: ~/ui-components
      docker:
        - image: circleci/node:14
          environment:
            ENV: CI
      steps:
        - checkout
        - restore_cache:
            key: node-v1-{{ checksum "package.json" }}-{{ arch }}

        - run: npm install

        - save_cache:
            key: node-v1-{{ checksum "package.json" }}-{{ arch }}
            paths:
              - node_modules

        - run:
            working_directory: ~/ui-components
            name: Run production build
            command: npm run build
workflows:
  version: 2
  build_and_test:
    jobs:
      - js_test
      - js_build
