version: 2.1

executors:
  node14:
    docker:
      - image: circleci/node:14
        environment:
          ENV: CI
    working_directory: ~/

commands:
  js_test:
    description: "Checkout and run JavaScript tests"
    steps:
      - checkout
      - run: npm install
      - run:
          working_directory: ~/
          name: Run JavaScript tests
          command: npm run test
          environment:
            JEST_JUNIT_OUTPUT_DIR: "./reports"

jobs:
  test-14:
    executor: node14
    steps:
      - js_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-14
