version: 2.1

executors:
  node14:
    docker:
      - image: circleci/node:14
        environment:
          ENV: CI
    working_directory: ~/ui-components
  node10:
    docker:
      - image: circleci/node:10
        environment:
          ENV: CI
    working_directory: ~/ui-components

commands:
  js_test:
    description: "Checkout and run JavaScript tests"
    steps:
      - checkout
      - run: yarn install
      - run:
          working_directory: ~/ui-components
          name: Run JavaScript tests
          command: yarn run test-ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "./reports"

  build:
    description: "Build npm library"
    steps:
      - checkout
      - run: yarn install
      - run:
          working_directory: ~/ui-components
          name: Run build
          command: yarn run build


  publish:
    description: "Publish to npm registry"
    steps:
      - checkout
      - run: yarn install
      - run:
          working_directory: ~/ui-components
          name: Run build
          command: yarn run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/ui-components/.npmrc
      - run: npm publish --access public --non-interactive

jobs:
  test-14:
    executor: node14
    steps:
      - js_test
      - build
  test-10:
    executor: node10
    steps:
      - js_test
      - build

  publish-14:
    executor: node14
    steps:
      - publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-14
      - test-10
  build_and_publish:
    jobs:
      - publish-14:
          filters:
            branches:
              only:
                - master
              ignore: /pull\/[0-9]+/
